{
 "title": "Dashboard Row",
 "panels": [
  {
   "title": "Process Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "cilium_process_resident_memory_bytes{kubernetes_pod_name=\"$pod\"}",
     "legendFormat": "process_resident_memory_bytes"
    },
    {
     "expr": "cilium_process_virtual_memory_bytes{kubernetes_pod_name=\"$pod\"}",
     "legendFormat": "process_virtual_memory_bytes"
    }
   ]
  },
  {
   "title": "Process FD Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cilium_process_open_fds{kubernetes_pod_name=\"$pod\"}",
     "legendFormat": "process_open_fds"
    }
   ]
  }
 ]
}
{
 "title": "Dashboard Row",
 "panels": [
  {
   "title": "Cilium Drop Count (INGRESS)",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cilium_drop_count_total{direction=\"INGRESS\", kubernetes_pod_name=\"$pod\"}",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "Cilium Drop Count (EGRESS)",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cilium_drop_count_total{direction=\"EGRESS\",kubernetes_pod_name=\"$pod\"}",
     "legendFormat": "{{  reason }}"
    }
   ]
  }
 ]
}
{
 "title": "L7 metrics",
 "panels": [
  {
   "title": "L7 Requests",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cilium_policy_l7_denied_total{kubernetes_pod_name=\"$pod\"}",
     "legendFormat": "L7_denied_total"
    },
    {
     "expr": "cilium_policy_l7_forwarded_total{kubernetes_pod_name=\"$pod\"}",
     "legendFormat": "L7_forwarded_total"
    }
   ]
  },
  {
   "title": "L7 Parse Errors",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cilium_policy_l7_parse_errors_total{kubernetes_pod_name=\"$pod\"}",
     "legendFormat": "l7_parse_errors"
    }
   ]
  }
 ]
}
{
 "title": "Dashboard Row",
 "panels": [
  {
   "title": "Policy Version History",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cilium_policy_max_revision{kubernetes_pod_name=\"$pod\"}",
     "legendFormat": "policy revisions"
    }
   ]
  },
  {
   "title": "Cilium Policy",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cilium_policy_count{kubernetes_pod_name=\"$pod\"}",
     "legendFormat": "policy_count"
    },
    {
     "expr": "cilium_policy_import_errors{kubernetes_pod_name=\"$pod\"}",
     "legendFormat": "policy_import_errors"
    }
   ]
  }
 ]
}
{
 "title": "Dashboard Row",
 "panels": [
  {
   "title": "Cilium Endpoint",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cilium_endpoint_count{kubernetes_pod_name=\"$pod\"}",
     "legendFormat": "cilium_endpoint_count"
    }
   ]
  },
  {
   "title": "Total Endpoint Regenerations",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cilium_endpoint_regenerations{kubernetes_pod_name=\"$pod\"}",
     "legendFormat": "endpoint_regenerations"
    }
   ]
  }
 ]
}
{
 "title": "Dashboard Row",
 "panels": [
  {
   "title": "Controllers Failing",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cilium_controllers_failing{kubernetes_pod_name=\"$pod\"}",
     "legendFormat": "controllers_failing"
    }
   ]
  }
 ]
}